[package]
name = "xcutils-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wee-alloc = false

[dependencies]
wasm-bindgen = "0.2"
prost = "0.11"
prost-types = "0.11"
regex = "1"
lazy_static = "1.4"