use super::core::{ProtoMessage, ProtoEnum};

pub fn generate_class(class_name: &str, message: &ProtoMessage) -> String {
    let mut result = String::new();
    
    // 文件头
    result.push_str(&format!(
        "//\n//  {}.swift\n//  Generated by xcutils\n//\n\n",
        class_name
    ));
    
    // 导入语句
    result.push_str("import Foundation\nimport ObjectMapper\n\n");
    
    // 类定义
    result.push_str(&format!("class {}: BaseModel {{\n", class_name));
    
    // 属性定义
    for field in &message.fields {
        if let Some(comment) = &field.comment {
            result.push_str(&format!("    /// {}\n", comment));
        }
        
        let type_name = convert_type(&field.type_name, field.is_repeated);
        let field_name = super::core::to_camel_case(&field.original_name);
        result.push_str(&format!("    var {}: {}?\n", field_name, type_name));
    }
    
    result.push_str("\n");
    
    // mapping方法
    result.push_str("    override func mapping(map: Map) {\n");
    result.push_str("        super.mapping(map: map)\n");
    
    for field in &message.fields {
        let field_name = super::core::to_camel_case(&field.original_name);
        result.push_str(&format!("        {} <- map[\"{}\"]\n", field_name, field.original_name));
    }
    
    result.push_str("    }\n");
    result.push_str("}\n");
    
    result
}

pub fn generate_enum(enum_name: &str, proto_enum: &ProtoEnum) -> String {
    let mut result = String::new();
    
    // 文件头
    result.push_str(&format!(
        "//\n//  {}.swift\n//  Generated by xcutils\n//\n\n",
        enum_name
    ));
    
    // 导入语句
    result.push_str("import Foundation\n\n");
    
    // 枚举定义
    result.push_str(&format!("enum {}: Int {{\n", enum_name));
    
    // 枚举值
    for value in &proto_enum.values {
        if let Some(comment) = &value.comment {
            result.push_str(&format!("    /// {}\n", comment));
        }
        result.push_str(&format!("    case {} = {}\n", value.name, value.value));
    }
    
    // fromValue方法
    result.push_str("\n    static func fromValue(_ value: Int) -> Self? {\n");
    result.push_str(&format!("        return {}(rawValue: value)\n", enum_name));
    result.push_str("    }\n");
    
    result.push_str("}\n");
    
    result
}

fn convert_type(proto_type: &str, is_repeated: bool) -> String {
    let base_type = match proto_type.to_lowercase().as_str() {
        "int32" | "int64" | "uint32" | "uint64" | "sint32" | "sint64" => "Int",
        "float" | "double" => "Double",
        "bool" => "Bool",
        "string" => "String",
        _ => proto_type,
    };
    
    if is_repeated {
        format!("[{}]", base_type)
    } else {
        base_type.to_string()
    }
}